kafka.bootstrap-servers=localhost:9092
kafka.topic.movie-rating=movie-rating-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#MongoDB Properties
spring.data.mongodb.host: 127.0.0.1
spring.data.mongodb.port: 27017
spring.data.mongodb.database: MovieService
