kafka.bootstrap-servers=localhost:9092
kafka.topic.movie-info=movie-info-topic
kafka.topic.movie-rating=movie-rating-topic

#MongoDB Properties
spring.data.mongodb.host: 127.0.0.1
spring.data.mongodb.port: 27017
spring.data.mongodb.database: MovieService

